version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: sandbox/aws-ecs@0.0.1
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_PREFIX}"
          region: ${AWS_REGION}
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: "${AWS_RESOURCE_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_PREFIX}-service,tag=${CIRCLE_SHA1}"
